#lang rosette

(require "../util.rkt" "../sql.rkt" "../table.rkt"  "../evaluator.rkt" "../equal.rkt" "../cosette.rkt")

(define INDIV_SAMPLE_SF (Table "INDIV_SAMPLE_SF" (list "ID" "TX_AMT" "DESCRIPTION") (gen-sym-schema 3 1)))

(define q1s (SELECT (VALS "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF.CMTE_ID" "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF.TRANSACTION_AMT" "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF.NAME" "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF.ID" "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF.TX_AMT" "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF.DESCRIPTION") FROM (AS (LEFT-OUTER-JOIN (NAMED INDIV_SAMPLE_NYC) (NAMED INDIV_SAMPLE_SF) (BINOP "INDIV_SAMPLE_NYC.CMTE_ID" = "INDIV_SAMPLE_SF.ID")) [ "INDIV_SAMPLE_NYC_JOIN_INDIV_SAMPLE_SF" (list "CMTE_ID" "TRANSACTION_AMT" "NAME" "ID" "TX_AMT" "DESCRIPTION") ]) WHERE (TRUE)))

(define q2s (SELECT (VALS "INDIV_SAMPLE_NYC.CMTE_ID" "INDIV_SAMPLE_NYC.NAME") FROM (NAMED INDIV_SAMPLE_NYC) WHERE (TRUE)))


(let* ([model (verify (same q1s q2s))]
	   [concrete-t1 (clean-ret-table (evaluate INDIV_SAMPLE_SF model))])
	(println concrete-t1)
)